version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    executor:
      name: 'node/default'
      tag: '13.11'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          cache-version: 'v2'
          override-ci-command: npm install
      - run:
          command: npm run test
workflows:
    build-and-test:
      jobs:
        - build-and-test